export const PROFILE_SET_MONEY = 'PROFILE_SET_MONEY'
export const PROFILE_SET_MONEY_EARNED = 'PROFILE_SET_MONEY_EARNED'
export const PROFILE_SET_CHARACTER = 'PROFILE_SET_CHARACTER'
export const PROFILE_SET_CHARACTER_CHOICES = 'PROFILE_SET_CHARACTER_CHOICES'
export const PROFILE_SET_AUTOBUY = 'PROFILE_SET_AUTOBUY'
export const PROFILE_SET_INVENTORY = 'PROFILE_SET_INVENTORY'

export const AUTH_SET_IS_LOGGED_IN = 'AUTH_SET_IS_LOGGED_IN'
export const AUTH_SET_XSTOKEN = 'AUTH_SET_XSTOKEN'

export const TRACKER_ADD_ITEM = 'TRACKER_ADD_ITEM'
export const TRACKER_REMOVE_ITEM = 'TRACKER_REMOVE_ITEM'
export const TRACKER_UPDATE_ALERT = 'TRACKER_UPDATE_ALERT'

export const HISTORY_ADD = 'HISTORY_ADD'
export const HISTORY_CLEAR = 'HISTORY_CLEAR'
export const HISTORY_LOST_ADD = 'HISTORY_LOST_ADD'
export const HISTORY_INRC_UNREAD = 'HISTORY_INRC_UNREAD'
export const HISTORY_CLEAR_UNREAD = 'HISTORY_CLEAR_UNREAD'

export const TAB_CHANGE = 'TAB_CHANGE'

export const AUCTIONS_SET = 'AUCTIONS_SET'
